In [ ]:
import sqlite3 as ps
import pandas as pd
import numpy as np

def fetch_database():
  conn = ps.connect('war.db')
  Cursor = conn.cursor()
  Cursor.execute('''CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,age INTEGER)''')


  Cursor.execute('SELECT COUNT(*) FROM users')
  if Cursor.fetchone()[0] == 0:
    Cursor.execute("INSERT INTO users (name,age) VALUES ('ALICE',25)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('BOB',30)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('CHARLIE',35)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('DAVID',40)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('EVE',28)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('FRANK',55)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('GRACE',32)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('HEIDI',29)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('IVAN',48)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('JUDY',37)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('KARL',60)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('LISA',23)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('MIKE',41)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('NINA',33)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('OSCAR',50)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('PAM',27)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('QUINN',39)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('RACHEL',45)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('STEVE',52)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('TINA',26)")
    conn.commit()

  Cursor.execute("SELECT * FROM users")
  rows = Cursor.fetchall()
  df = pd.DataFrame(rows, columns=['id', 'name', 'age'])
  conn.close()
  return df

In [ ]:
df_users = fetch_database()
display(df_users)

    id     name  age
0    1    ALICE   25
1    2      BOB   30
2    3  CHARLIE   35
3    4    DAVID   40
4    5      EVE   28
5    6    FRANK   55
6    7    GRACE   32
7    8    HEIDI   29
8    9     IVAN   48
9   10     JUDY   37
10  11     KARL   60
11  12     LISA   23
12  13     MIKE   41
13  14     NINA   33
14  15    OSCAR   50
15  16      PAM   27
16  17    QUINN   39
17  18   RACHEL   45
18  19    STEVE   52
19  20     TINA   26

In [ ]:
df_users['marks'] = np.random.randint(50, 100, size=len(df_users))
print("DataFrame after adding 'marks' column:")
display(df_users)

DataFrame after adding 'marks' column:

    id     name  age  marks
0    1    ALICE   25     75
1    2      BOB   30     50
2    3  CHARLIE   35     95
3    4    DAVID   40     80
4    5      EVE   28     79
5    6    FRANK   55     76
6    7    GRACE   32     60
7    8    HEIDI   29     83
8    9     IVAN   48     56
9   10     JUDY   37     55
10  11     KARL   60     63
11  12     LISA   23     94
12  13     MIKE   41     83
13  14     NINA   33     77
14  15    OSCAR   50     95
15  16      PAM   27     78
16  17    QUINN   39     97
17  18   RACHEL   45     88
18  19    STEVE   52     96
19  20     TINA   26     75

In [ ]:
import sqlite3 as ps
import pandas as pd
import numpy as np

def fetch_database():
  conn = ps.connect('war.db')
  Cursor = conn.cursor()
  Cursor.execute('''CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,age INTEGER)''')


  Cursor.execute('SELECT COUNT(*) FROM users')
  if Cursor.fetchone()[0] == 0:
    Cursor.execute("INSERT INTO users (name,age) VALUES ('ALICE',25)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('BOB',30)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('CHARLIE',35)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('DAVID',40)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('EVE',28)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('FRANK',55)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('GRACE',32)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('HEIDI',29)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('IVAN',48)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('JUDY',37)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('KARL',60)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('LISA',23)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('MIKE',41)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('NINA',33)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('OSCAR',50)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('PAM',27)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('QUINN',39)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('RACHEL',45)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('STEVE',52)")
    Cursor.execute("INSERT INTO users (name,age) VALUES ('TINA',26)")
    conn.commit()

  Cursor.execute("SELECT * FROM users")
  rows = Cursor.fetchall()
  df = pd.DataFrame(rows, columns=['id', 'name', 'age'])
  conn.close()
  return df

try:
    df_sorted_by_age = df_users.sort_values(by='age', ascending=False)
except NameError:

    print("df_users not found, recreating it...")
    df_users = fetch_database()
    df_users['marks'] = np.random.randint(50, 100, size=len(df_users))
    df_sorted_by_age = df_users.sort_values(by='age', ascending=False)

print("DataFrame sorted by age (descending):")
display(df_sorted_by_age)

DataFrame sorted by age (descending):

    id     name  age  marks
10  11     KARL   60     63
5    6    FRANK   55     76
18  19    STEVE   52     96
14  15    OSCAR   50     95
8    9     IVAN   48     56
17  18   RACHEL   45     88
12  13     MIKE   41     83
3    4    DAVID   40     80
16  17    QUINN   39     97
9   10     JUDY   37     55
2    3  CHARLIE   35     95
13  14     NINA   33     77
6    7    GRACE   32     60
1    2      BOB   30     50
7    8    HEIDI   29     83
4    5      EVE   28     79
15  16      PAM   27     78
19  20     TINA   26     75
0    1    ALICE   25     75
11  12     LISA   23     94

In [ ]:
mean_marks = df_users['marks'].mean()
print(f"Mean marks: {mean_marks:.2f}")

Mean marks: 77.75

In [ ]:
candidates_above_mean = df_users[df_users['marks'] > mean_marks]['name'].sort_values().tolist()
print("Candidates who scored more than the mean marks (sorted alphabetically):")
print(candidates_above_mean)

Candidates who scored more than the mean marks (sorted alphabetically):
['CHARLIE', 'DAVID', 'EVE', 'HEIDI', 'LISA', 'MIKE', 'OSCAR', 'PAM', 'QUINN', 'RACHEL', 'STEVE']

In [ ]:
import sqlite3 as ps
import pandas as pd
import numpy as np

!pip install Faker --quiet

from faker import Faker

fake = Faker()

### Create Student Database

In [ ]:
def create_student_database(db_name='university.db', num_students=100):
    conn = ps.connect(db_name)
    Cursor = conn.cursor()

    Cursor.execute('''
        CREATE TABLE IF NOT EXISTS students (
            student_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name_of_the_student TEXT,
            course_of_btech TEXT,
            cgpa REAL,
            email_id TEXT
        )
    ''')
    conn.commit()


    Cursor.execute('SELECT COUNT(*) FROM students')
    if Cursor.fetchone()[0] == 0:
        courses = ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
        student_data = []
        for _ in range(num_students):
            name = fake.name()
            course = np.random.choice(courses)
            cgpa = round(np.random.uniform(6.0, 10.0), 2)
            email = fake.email()
            student_data.append((name, course, cgpa, email))

        Cursor.executemany("INSERT INTO students (name_of_the_student, course_of_btech, cgpa, email_id) VALUES (?, ?, ?, ?)", student_data)
        conn.commit()

    Cursor.execute("SELECT * FROM students")
    rows = Cursor.fetchall()
    df_students = pd.DataFrame(rows, columns=['student_id', 'name_of_the_student', 'course_of_btech', 'cgpa', 'email_id'])
    conn.close()
    return df_students

df_students = create_student_database()
print("Student Database created and populated (if empty):")
display(df_students.head())

Student Database created and populated (if empty):

,student_id,name_of_the_student,course_of_btech,cgpa,email_id
0,1,Crystal Collins,Computer Science,8.87,barbarapatrick@example.org
1,2,Taylor Spencer,Computer Science,9.78,michael82@example.net
2,3,William Jones,Computer Science,7.29,spencer12@example.com
3,4,Stephen Richardson,Mechanical Engineering,8.20,zrussell@example.net
4,5,Kevin Herrera,Computer Science,9.92,nathan81@example.org

### Create Faculty Database

In [ ]:
def create_faculty_database(db_name='university.db', num_faculty=3):
    conn = ps.connect(db_name)
    Cursor = conn.cursor()

    Cursor.execute('''
        CREATE TABLE IF NOT EXISTS faculty (
            faculty_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name_of_faculty TEXT,
            subject TEXT,
            experience INTEGER,
            salary REAL
        )
    ''')
    conn.commit()

    Cursor.execute('SELECT COUNT(*) FROM faculty')
    if Cursor.fetchone()[0] == 0:

        subjects = ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering']
        faculty_data = []
        for i in range(num_faculty):
            name = fake.name()
            subject = subjects[i]
            experience = np.random.randint(5, 25)
            salary = 0.0
            faculty_data.append((name, subject, experience, salary))

        Cursor.executemany("INSERT INTO faculty (name_of_faculty, subject, experience, salary) VALUES (?, ?, ?, ?)", faculty_data)
        conn.commit()

    Cursor.execute("SELECT * FROM faculty")
    rows = Cursor.fetchall()
    df_faculty = pd.DataFrame(rows, columns=['faculty_id', 'name_of_faculty', 'subject', 'experience', 'salary'])
    conn.close()
    return df_faculty

df_faculty = create_faculty_database()
print("Faculty Database created and populated (if empty):")
display(df_faculty.head())

Faculty Database created and populated (if empty):

   faculty_id   name_of_faculty                 subject  experience  salary
0           1  Daniel Rodriguez        Computer Science          12     0.0
1           2         Emma Haas  Electrical Engineering          11     0.0
2           3      Karen Prince  Mechanical Engineering          22     0.0

### Calculate Faculty Salaries

In [ ]:
FEE_PER_STUDENT = 500

student_counts_by_subject = df_students.groupby('course_of_btech').size().reset_index(name='num_students')
student_counts_by_subject.rename(columns={'course_of_btech': 'subject'}, inplace=True)

df_faculty_with_counts = pd.merge(df_faculty, student_counts_by_subject, on='subject', how='left')

df_faculty_with_counts['num_students'] = df_faculty_with_counts['num_students'].fillna(0).astype(int)

df_faculty_with_counts['salary'] = df_faculty_with_counts['num_students'] * FEE_PER_STUDENT

print("Faculty salaries calculated based on student enrollment:")
display(df_faculty_with_counts)

Faculty salaries calculated based on student enrollment:

,faculty_id,name_of_faculty,subject,experience,salary,num_students
0,1,Daniel Rodriguez,Computer Science,12,15000,30
1,2,Emma Haas,Electrical Engineering,11,14500,29
2,3,Karen Prince,Mechanical Engineering,22,9500,19

### Join Student and Faculty Data

In [ ]:
df_students_renamed = df_students.rename(columns={'course_of_btech': 'subject'})

df_students_with_faculty = pd.merge(df_students_renamed,
                                    df_faculty_with_counts[['subject', 'name_of_faculty', 'faculty_id', 'salary']],
                                    on='subject',
                                    how='left')

print("Students mapped to their faculty:")
display(df_students_with_faculty.head())

Students mapped to their faculty:

,student_id,name_of_the_student,subject,cgpa,email_id,name_of_faculty,faculty_id,salary
0,1,Crystal Collins,Computer Science,8.87,barbarapatrick@example.org,Daniel Rodriguez,1.0,15000.0
1,2,Taylor Spencer,Computer Science,9.78,michael82@example.net,Daniel Rodriguez,1.0,15000.0
2,3,William Jones,Computer Science,7.29,spencer12@example.com,Daniel Rodriguez,1.0,15000.0
3,4,Stephen Richardson,Mechanical Engineering,8.20,zrussell@example.net,Karen Prince,3.0,9500.0
4,5,Kevin Herrera,Computer Science,9.92,nathan81@example.org,Daniel Rodriguez,1.0,15000.0