In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url ="https://books.toscrape.com/index.html"

Response =requests.get(url)

soup = BeautifulSoup(Response.text,"html.parser")

books = soup.find_all("article", class_="product_pod")
print(books[0])
data = []

for book in books:
   title = book.find("h3").find("a")["title"]
   price = book.find("p",class_="price_color").text
   rating = book.find("p",class_="star-rating")["class"][1]

   data.append([title,price,rating])

df = pd.DataFrame(data,columns=["Title","Price","Rating"])
df.to_csv("books.csv",index=False)

print(df.head())

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
                                   Title    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

### Calculate Mean Price and Find Books at Mean Price

In [ ]:
lower_bound = 34.0
upper_bound = 40.0

books_in_custom_range = df[
    (df['Cleaned_Price'] >= lower_bound) &
    (df['Cleaned_Price'] <= upper_bound)
]

if not books_in_custom_range.empty:
    print(f"\nBooks priced between £{lower_bound:.2f} and £{upper_bound:.2f} (Mean Price: £{mean_price:.2f}):")
    display(books_in_custom_range[['Title', 'Price', 'Rating', 'Cleaned_Price']])
else:
    print(f"\nNo books found with prices between £{lower_bound:.2f} and £{upper_bound:.2f} (Mean Price: £{mean_price:.2f}).")

Books priced between £34.00 and £40.00 (Mean Price: £38.05):

,Title,Price,Rating,Cleaned_Price
14,Rip it Up and Start Again,Â£35.02,Five,35.02
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,37.59

### Top-Rated Books (5-star and 4-star)

In [ ]:

top_rated_books = df[df['Rating'].isin(['Five', 'Four'])]

if not top_rated_books.empty:
    print("\nTop-rated books (5-star and 4-star):")
    rating_map = {'Five': 5, 'Four': 4, 'Three': 3, 'Two': 2, 'One': 1}
    top_rated_books['Numeric_Rating'] = top_rated_books['Rating'].map(rating_map)
    top_rated_books = top_rated_books.sort_values(by='Numeric_Rating', ascending=False).drop(columns=['Numeric_Rating'])

    display(top_rated_books[['Title', 'Price', 'Rating']])
else:
    print("\nNo books found with 5-star or 4-star ratings.")

Top-rated books (5-star and 4-star):

/tmp/ipykernel_2490/2705239771.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_rated_books['Numeric_Rating'] = top_rated_books['Rating'].map(rating_map)

                                                Title    Price Rating
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
14                          Rip it Up and Start Again  Â£35.02   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
12                                        Set Me Free  Â£17.46   Five
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
3                                       Sharp Objects  Â£47.82   Four
11                              Shakespeare's Sonnets  Â£20.66   Four

### Books with 1-Star Rating

### Books with the Lowest Prices

In [ ]:
lowest_priced_books = df.sort_values(by='Cleaned_Price', ascending=True).head(5)

if not lowest_priced_books.empty:
    print("\nBooks with the 5 lowest prices:")
    display(lowest_priced_books[['Title', 'Price', 'Rating', 'Cleaned_Price']])
else:
    print("\nNo books found.")

Books with the 5 lowest prices:

,Title,Price,Rating,Cleaned_Price
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,13.99
12,Set Me Free,Â£17.46,Five,17.46
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,17.93
11,Shakespeare's Sonnets,Â£20.66,Four,20.66
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,22.60

In [ ]:

lowest_rated_books = df[df['Rating'] == 'One']

if not lowest_rated_books.empty:
    print("\nBooks with 1-star rating:")
    display(lowest_rated_books[['Title', 'Price', 'Rating']])
else:
    print("\nNo books found with a 1-star rating.")

Books with 1-star rating:

                                                Title    Price Rating
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
5                                     The Requiem Red  Â£22.65    One
9                                     The Black Maria  Â£52.15    One
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One